/**
 * Downloadable PNG "player card" (US-009/FR-8). Renders a dark card with
 * username, avatar, global rank, pp, accuracy and grade counts to a canvas,
 * then triggers a normal browser download — no server round-trip.
 */
(function (global) {
  'use strict';

  const OsuEnhancer = (global.OsuEnhancer = global.OsuEnhancer || {});
  const sel = OsuEnhancer.selectors;

  const CARD_W = 900;
  const CARD_H = 420;
  const GRADE_COLORS = { ssh: '#ddeeff', ss: '#f5d76e', sh: '#e0e0e0', s: '#f2c744', a: '#88d97a' };

  function textOf(el) {
    return el ? el.textContent.trim() : null;
  }

  /** Finds a value near an element whose own text matches `label` (case-insensitive). */
  function findStatByLabel(label) {
    const needle = label.toLowerCase();
    const candidates = document.querySelectorAll(`${sel.profileDetail} *`);
    for (const el of candidates) {
      if (el.children.length === 0 && el.textContent.trim().toLowerCase() === needle) {
        const container = el.parentElement;
        const valueEl = container && container.querySelector('div:last-child, span:last-child');
        if (valueEl && valueEl !== el) return valueEl.textContent.trim();
      }
    }
    return null;
  }

  function getGradeCounts() {
    const counts = {};
    document.querySelectorAll(sel.profileRankCountItem).forEach((item) => {
      const pill = item.querySelector(sel.scoreRankPill);
      const number = textOf(item.querySelector('div:last-child'));
      if (!pill) return;
      const rankClass = Array.from(pill.classList).find((c) => c.startsWith('score-rank--rank-'));
      if (rankClass) counts[rankClass.replace('score-rank--rank-', '')] = number;
    });
    return counts;
  }

  function loadImage(url) {
    return new Promise((resolve) => {
      if (!url) return resolve(null);
      const img = new Image();
      img.crossOrigin = 'anonymous';
      img.onload = () => resolve(img);
      img.onerror = () => resolve(null);
      img.src = url;
    });
  }

  function roundRect(ctx, x, y, w, h, r) {
    ctx.beginPath();
    ctx.moveTo(x + r, y);
    ctx.arcTo(x + w, y, x + w, y + h, r);
    ctx.arcTo(x + w, y + h, x, y + h, r);
    ctx.arcTo(x, y + h, x, y, r);
    ctx.arcTo(x, y, x + w, y, r);
    ctx.closePath();
  }

  async function buildCardCanvas(meta) {
    const canvas = document.createElement('canvas');
    canvas.width = CARD_W;
    canvas.height = CARD_H;
    const ctx = canvas.getContext('2d');

    // Background.
    const bg = ctx.createLinearGradient(0, 0, CARD_W, CARD_H);
    bg.addColorStop(0, '#1a1a24');
    bg.addColorStop(1, '#12121a');
    ctx.fillStyle = bg;
    roundRect(ctx, 0, 0, CARD_W, CARD_H, 24);
    ctx.fill();

    // Avatar.
    const avatar = await loadImage(meta.avatarUrl);
    const avatarSize = 140;
    const avatarX = 40;
    const avatarY = 40;
    ctx.save();
    roundRect(ctx, avatarX, avatarY, avatarSize, avatarSize, 16);
    ctx.clip();
    if (avatar) {
      ctx.drawImage(avatar, avatarX, avatarY, avatarSize, avatarSize);
    } else {
      ctx.fillStyle = '#333';
      ctx.fillRect(avatarX, avatarY, avatarSize, avatarSize);
    }
    ctx.restore();

    // Username.
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 40px "Segoe UI", sans-serif';
    ctx.fillText(meta.username, avatarX + avatarSize + 30, avatarY + 50);

    // Stats.
    ctx.font = '22px "Segoe UI", sans-serif';
    ctx.fillStyle = '#ff66ab';
    const stats = [
      `Global Rank: ${meta.rank || '—'}`,
      `PP: ${meta.pp || '—'}`,
      `Accuracy: ${meta.accuracy || '—'}`,
    ];
    stats.forEach((line, i) => {
      ctx.fillText(line, avatarX + avatarSize + 30, avatarY + 95 + i * 32);
    });

    // Grade pills.
    let gx = 40;
    const gy = avatarY + avatarSize + 50;
    ctx.font = 'bold 20px "Segoe UI", sans-serif';
    Object.entries(meta.grades).forEach(([grade, count]) => {
      const color = GRADE_COLORS[grade] || '#999';
      ctx.fillStyle = color;
      roundRect(ctx, gx, gy, 90, 44, 10);
      ctx.fill();
      ctx.fillStyle = '#141414';
      ctx.textAlign = 'center';
      ctx.fillText(`${grade.toUpperCase()} ${count || 0}`, gx + 45, gy + 29);
      ctx.textAlign = 'left';
      gx += 100;
    });

    // Footer watermark.
    ctx.fillStyle = '#666';
    ctx.font = '14px "Segoe UI", sans-serif';
    ctx.fillText('generated by osu! Enhancer', 40, CARD_H - 24);

    return canvas;
  }

  async function downloadPlayerCard() {
    const profileMeta = OsuEnhancer.profile.getProfileMeta();
    const meta = {
      ...profileMeta,
      rank: findStatByLabel('classement global') || findStatByLabel('global ranking') || findStatByLabel('global rank'),
      pp: findStatByLabel('pp'),
      accuracy: findStatByLabel('hit accuracy') || findStatByLabel('précision') || findStatByLabel('accuracy'),
      grades: getGradeCounts(),
    };

    const canvas = await buildCardCanvas(meta);
    const url = canvas.toDataURL('image/png');
    const link = document.createElement('a');
    link.href = url;
    link.download = `${meta.username || 'player'}-playercard.png`;
    document.body.appendChild(link);
    link.click();
    link.remove();
  }

  OsuEnhancer.playerCard = { downloadPlayerCard };
})(typeof window !== 'undefined' ? window : globalThis);
